version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    container_name: flask-mysql
    environment:
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin123'
      MYSQL_DATABASE: 'flask-crud'
      MYSQL_ROOT_PASSWORD: 'admin123'
    ports:
      - "3306:3306" # Corrigido: espaço após o hífen
    volumes:
      - mysql_data:/var/lib/mysql # Volume nomeado (recomendado)
      - ./mysql/initdb:/docker-entrypoint-initdb.d # Para scripts SQL iniciais
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysql_data:
